# -*- coding: utf-8 -*-
"""Untitled1-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Qy0tabeIK39VXIxSJRPUH9O2JiKAMe4
"""

import pandas as pd
import numpy as np

df= pd.read_csv('LIWC-22 Results - final_full_post_processed_equa___ - LIWC Analysis.csv')

def combine_consecutive_rows(df):
    combined_rows = []
    prev_row = df.iloc[0]

    for i in range(1, df.shape[0]):
        current_row = df.iloc[i]
        if current_row['speaker'] == prev_row['speaker']:
            prev_row['Analytic'] += current_row['Analytic']
            prev_row['Clout'] += current_row['Clout']
            prev_row['Authentic'] += current_row['Authentic']
            prev_row['Tone'] += current_row['Tone']
        else:
            combined_rows.append(prev_row)
            prev_row = current_row

    combined_rows.append(prev_row)  # Append the last row

    return pd.DataFrame(combined_rows)

final_result = []
for i in list(set(df.filename)):
    temp = df[df.filename==i][['speaker', 'Analytic',"Clout",
                               "Authentic",'Tone']].fillna(0)
    temp = combine_consecutive_rows(temp)

    st = temp[temp.speaker=='student']
    te = temp[temp.speaker=='instructor']

    if st.shape[0] != te.shape[0]:
      len = min(st.shape[0], te.shape[0])
      st = st[:len]
      te = te[:len]
    else:
      None

    snchrony = []
    for k, v in zip(st.drop(columns=['speaker']).values,
                   te.drop(columns=['speaker']).values):
        distance = np.linalg.norm(k - v)
        snchrony.append(distance)
    st['filename'] = i
    st['score'] = snchrony
    final_result.append(st)

pd.concat(final_result).to_excel('final_result.xlsx')

pd.concat(final_result).groupby('filename')['score'].mean(
).to_excel('final_result_ave.xlsx')

